### ISSUE TITLE
Examples are not working

### ISSUE THREAD

**Issue by rohanvbhatnagar** [playlyfe/playlyfe-php-sdk#4]
The examples for client-credential authentication and auth-code flow both are not working.

The error which I get for runtime routes in v2 are: `The player account was removed by it's owner` for both auth strategies.

**Comment by adahox** [comment]
i'm actually getting the same error. has some fix to it?

**Comment by pyros2097** [comment]
Oh.. I thought this was fixed... Since Rohan was an intern here... I'll get on it..

**Comment by pyros2097** [comment]
Yeah I fixed them .. I've added more information on the Readme page so you can run them easily now
